After an update from beta-1103 to beta-2423 multiple `main()`s within a single package do not work anymore.

You might execute "Rebuild Project", change the string in one of the `main()`s and run it to trigger the error.

Error message:

>Error:(3, 1) Kotlin: 'public fun main(args: kotlin.Array<kotlin.String>): kotlin.Unit' is already defined in foo

`foo/a.kt`:

```
package foo

fun main(args: Array<String>) = println("a")
```

`foo/b.kt`:

```
package foo

fun main(args: Array<String>) = println("b")
```


